name: Build and test

on: [push, pull_request]

jobs:
  ubuntu-build:
    name: Build - Ubuntu
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        build_type: [Debug, Release]
        compiler: [{c: gcc, cxx: g++}]
        libbacktrace: ['-DVAL_USE_LIBBACKTRACE_BACKTRACE=OFF']
        include:
          - os: 'ubuntu-22.04'
            build_type: Release
            compiler: {c: clang, cxx: clang++}
            libbacktrace: '-DVAL_USE_LIBBACKTRACE_BACKTRACE=OFF'
          - os: 'ubuntu-22.04'
            build_type: Release
            compiler: {c: gcc, cxx: g++}
            libbacktrace: '-DVAL_USE_LIBBACKTRACE_BACKTRACE=ON'
          - os: 'ubuntu-22.04'
            build_type: Release
            compiler: {c: clang, cxx: clang++}
            libbacktrace: '-DVAL_USE_LIBBACKTRACE_BACKTRACE=ON'

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Install pip packages
      run: pip install -r third_party/requirements.txt
    
    - name: Download DPC++
      run: |
        cp /opt/ur/dpcpp/dpcpp_compiler.tar.gz ${{github.workspace}}/
        tar -xvf ${{github.workspace}}/dpcpp_compiler.tar.gz

    - name: Configure CMake
      run: >
        cmake
        -B${{github.workspace}}/build
        -DCMAKE_C_COMPILER=${{matrix.compiler.c}}
        -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
        -DUR_ENABLE_TRACING=ON
        -DUR_DEVELOPER_MODE=ON
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DUR_BUILD_TESTS=ON
        -DUR_FORMAT_CPP_STYLE=ON
        -DUR_DPCXX=${{github.workspace}}/dpcpp_compiler/bin/clang++
        ${{matrix.libbacktrace}}

    - name: Generate source from spec, check for uncommitted diff
      if: matrix.os == 'ubuntu-22.04'
      run: cmake --build ${{github.workspace}}/build --target check-generated

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure -L "python|umf|loader|validation|tracing|unit|urtrace"

  windows-build:
    name: Build - Windows
    strategy:
      matrix:
        os: ['windows-2019', 'windows-2022']
        build_type: [Debug, Release]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install prerequisites
      run: python3 -m pip install -r third_party/requirements.txt

    - name: Configure CMake
      run: >
        cmake
        -B${{github.workspace}}/build
        -DCMAKE_POLICY_DEFAULT_CMP0094=NEW
        -DUR_ENABLE_TRACING=ON
        -DUR_DEVELOPER_MODE=ON
        -DUR_BUILD_TESTS=ON
        -DUR_FORMAT_CPP_STYLE=ON

    - name: Generate source from spec, check for uncommitted diff
      if: matrix.os == 'windows-2022'
      run: cmake --build ${{github.workspace}}/build --target check-generated --config ${{matrix.build_type}}

    - name: Build all
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -j 2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure -L "python|umf|loader|validation|tracing|unit|urtrace"
